kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: true

prometheus:
  prometheusSpec:
    retention: 2d
    resources:
      requests:
        cpu: 150m
        memory: 300Mi
      limits:
        cpu: 400m
        memory: 600Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 500Mi

grafana:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  persistence:
    enabled: true
    storageClassName: local-path
    size: 500Mi
  adminPassword: "changeme-pfa"

defaultRules:
  rules:
    kubeApiserverAvailability: false
    kubeApiserverSlos: false
    etcd: false